links:
    - product: chrome
      url: https://crbug.com/698130
      results:
        - test: DOMParser-parseFromString-xml.html
    - product: chrome
      url: https://issues.chromium.org/issues/562303033
      results:
        - test: DOMParser-xml-character-entities.html
