links:
- product: firefox
  results:
  - subtest: 'CSS Animations: property <zoom> from [normal] to [3] at (-0.5) should
      be [1]'
    test: zoom-interpolation.html
  - subtest: 'Web Animations: property <zoom> from [normal] to [3] at (-0.5) should
      be [1]'
    test: zoom-interpolation.html
  - subtest: 'CSS Transitions: property <zoom> from [calc(sibling-index() * 100%)]
      to [2] at (1) should be [2]'
    test: zoom-interpolation.html
  - subtest: 'CSS Transitions with transition: all: property <zoom> from [calc(sibling-index()
      * 100%)] to [2] at (1) should be [2]'
    test: zoom-interpolation.html
  - subtest: 'CSS Animations: property <zoom> from [calc(sibling-index() * 100%)]
      to [2] at (0) should be [1]'
    test: zoom-interpolation.html
  - subtest: 'CSS Animations: property <zoom> from [calc(sibling-index() * 100%)]
      to [2] at (1) should be [2]'
    test: zoom-interpolation.html
  - subtest: 'Web Animations: property <zoom> from [calc(sibling-index() * 100%)]
      to [2] at (0) should be [1]'
    test: zoom-interpolation.html
  - subtest: 'Web Animations: property <zoom> from [calc(sibling-index() * 100%)]
      to [2] at (1) should be [2]'
    test: zoom-interpolation.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2038829
