links:
- product: firefox
  results:
  - subtest: .grid-lanes 1
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 2
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 3
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 4
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 5
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 6
    test: column-minimum-contribution-baseline-shim-vertical-lr.html
  - subtest: .grid-lanes 1
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 2
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 3
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 4
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 5
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 6
    test: column-minimum-contribution-baseline-shim-vertical-rl.html
  - subtest: .grid-lanes 1
    test: row-minimum-contribution-baseline-shim.html
  - subtest: .grid-lanes 2
    test: row-minimum-contribution-baseline-shim.html
  - subtest: .grid-lanes 3
    test: row-minimum-contribution-baseline-shim.html
  - subtest: .grid-lanes 4
    test: row-minimum-contribution-baseline-shim.html
  - subtest: .grid-lanes 5
    test: row-minimum-contribution-baseline-shim.html
  - subtest: .grid-lanes 6
    test: row-minimum-contribution-baseline-shim.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2026240
