links:
- results:
  - test: place-content-computed.html
  - test: place-content-invalid.html
  url: http://example.org
- product: chrome
  results:
  - test: align-items-valid.html
  - test: align-self-computed.html
  - test: justify-items-computed.html
  - test: align-content-valid.html
  - test: justify-items-valid.html
  - test: justify-self-valid.html
  - test: place-items-shorthand.html
  - test: place-self-shorthand.html
  - test: place-content-valid.html
  - test: place-items-computed.html
  - test: place-items-valid.html
  - test: place-self-computed.html
  - test: place-self-valid.html
  - test: place-content-shorthand.html
  - test: align-content-computed.html
  - test: align-items-computed.html
  - test: align-self-valid.html
  - test: justify-self-computed.html
  - test: place-content-computed.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=885175
- product: firefox
  results:
  - test: place-items-computed.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1887057
- product: firefox
  results:
  - subtest: e.style['align-items'] = "anchor-center" should not set the property
      value
    test: align-items-invalid.html
  - subtest: e.style['justify-items'] = "anchor-center" should not set the property
      value
    test: justify-items-invalid.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2058545
- product: firefox
  results:
  - subtest: Property align-content value 'flow-start'
    test: align-content-computed.html
  - subtest: Property align-content value 'flow-end'
    test: align-content-computed.html
  - subtest: Property align-content value 'safe flow-start'
    test: align-content-computed.html
  - subtest: Property align-content value 'unsafe flow-end'
    test: align-content-computed.html
  - subtest: Property align-items value 'flow-start'
    test: align-items-computed.html
  - subtest: Property align-items value 'flow-end'
    test: align-items-computed.html
  - subtest: Property align-items value 'safe flow-start'
    test: align-items-computed.html
  - subtest: Property align-items value 'unsafe flow-end'
    test: align-items-computed.html
  - subtest: Property align-self value 'flow-start'
    test: align-self-computed.html
  - subtest: Property align-self value 'flow-end'
    test: align-self-computed.html
  - subtest: Property align-self value 'safe flow-start'
    test: align-self-computed.html
  - subtest: Property align-self value 'unsafe flow-end'
    test: align-self-computed.html
  - subtest: Property justify-content value 'flow-start'
    test: justify-content-computed.html
  - subtest: Property justify-content value 'flow-end'
    test: justify-content-computed.html
  - subtest: Property justify-content value 'safe flow-start'
    test: justify-content-computed.html
  - subtest: Property justify-content value 'unsafe flow-end'
    test: justify-content-computed.html
  - subtest: Property justify-items value 'flow-start'
    test: justify-items-computed.html
  - subtest: Property justify-items value 'flow-end'
    test: justify-items-computed.html
  - subtest: Property justify-items value 'safe flow-start'
    test: justify-items-computed.html
  - subtest: Property justify-items value 'unsafe flow-end'
    test: justify-items-computed.html
  - subtest: Property justify-self value 'flow-start'
    test: justify-self-computed.html
  - subtest: Property justify-self value 'flow-end'
    test: justify-self-computed.html
  - subtest: Property justify-self value 'safe flow-start'
    test: justify-self-computed.html
  - subtest: Property justify-self value 'unsafe flow-end'
    test: justify-self-computed.html
  - subtest: Property place-content value 'flow-start'
    test: place-content-computed.html
  - subtest: Property place-content value 'flow-start flow-end'
    test: place-content-computed.html
  - subtest: Property place-items value 'flow-start'
    test: place-items-computed.html
  - subtest: Property place-items value 'flow-start flow-end'
    test: place-items-computed.html
  - subtest: Property place-self value 'flow-start'
    test: place-self-computed.html
  - subtest: Property place-self value 'flow-start flow-end'
    test: place-self-computed.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2076610
