links:
- product: safari
  results:
  - status: FAIL
    test: use-keyframes.html
  url: https://bugs.webkit.org/show_bug.cgi?id=173154
- product: safari
  results:
  - status: FAIL
    test: href-filter-element.html
  url: https://bugs.webkit.org/show_bug.cgi?id=201992
- product: webkitgtk
  results:
  - status: FAIL
    test: use-keyframes.html
  url: https://bugs.webkit.org/show_bug.cgi?id=173154
- product: webkitgtk
  results:
  - status: FAIL
    test: href-filter-element.html
  url: https://bugs.webkit.org/show_bug.cgi?id=201992
- product: firefox
  results:
  - test: url-reference-local-textpath.svg
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1634393
- product: chrome
  results:
  - test: href-filter-element.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=109212
- product: chrome
  results:
  - test: href-filter-element.html
  - test: use-descendant-combinator-003.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=1184034
- product: chrome
  results:
  - test: use-descendant-combinator-003.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=785246
- product: safari
  results:
  - test: url-processing-whitespace-003.svg
  - test: url-processing-whitespace-001.svg
  - test: url-processing-whitespace-002.svg
  url: https://bugs.webkit.org/show_bug.cgi?id=269522
- product: safari
  results:
  - test: use-descendant-combinator-003.html
  url: https://bugs.webkit.org/show_bug.cgi?id=249080
- product: firefox
  results:
  - test: media-fragment-spatial-overflow-clamped.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2041697
