links:
    - label: interop-2026-webcompat
      results:
        - test: new-scroll-event-dispatched-at-next-updating-rendering-time.html
    - product: chrome
      url: https://crbug.com/397737222
      results:
        - test: new-scroll-event-dispatched-at-next-updating-rendering-time.html
