links:
- product: chrome
  results:
  - test: hanging-scrollable-001.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=1212299
- product: chrome
  results:
  - test: hanging-scrollable-001.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=1219062
- product: firefox
  results:
  - test: hanging-punctuation-allow-end-001.xht
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1745420
- product: firefox
  results:
  - test: hanging-punctuation-block-bound-001.html
  - test: hanging-punctuation-inline-bound-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1782401
- product: firefox
  results:
  - test: '*'
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1253615
- product: firefox
  results:
  - test: hanging-punctuation-allow-end-basic.html
  - test: hanging-punctuation-allow-end-inlines.html
  - test: hanging-punctuation-allow-end.html
  - test: hanging-punctuation-first-and-last-together.html
  - test: hanging-punctuation-first-rtl.html
  - test: hanging-punctuation-first-whitespace.html
  - test: hanging-punctuation-first.html
  - test: hanging-punctuation-last-rtl.html
  - test: hanging-punctuation-last-whitespace.html
  - test: hanging-punctuation-last.html
  - test: hanging-punctuation-variable-font-size.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2020871
- product: firefox
  results:
  - test: hanging-punctuation-first-001.xht
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2021100
