links:
    - label: a11y
      results:
        - test: aria-labelledby.html
        - test: dom-mutation.html
        - test: label-descendant.html
        - test: label-for.html
    - label: accessibility
      results:
        - test: aria-labelledby.html
        - test: dom-mutation.html
        - test: label-descendant.html
        - test: label-for.html
