links:
    - product: chrome
      url: https://bugs.chromium.org/p/chromium/issues/detail?id=592830
      results:
        - test: src.html
    - product: chrome
      url: https://issues.chromium.org/issues/40256677
      results:
        - test: src.html
          subtest: HTMLTrackElement.src unresolvable value in content attribute
        - test: src.html
          subtest: HTMLTrackElement.src assigning unresolvable value to IDL attribute
