links:
- product: firefox
  results:
  - subtest: Parameter default resolves a dashed-function in the definition scope
    test: function-definition-scope.html
  - subtest: result resolves a dashed-function in the definition scope
    test: function-definition-scope.html
  - subtest: A local resolves a dashed-function in the definition scope
    test: function-definition-scope.html
  - subtest: Default referencing an earlier parameter
    test: function-parameter-scoping.html
  - subtest: em in a typed parameter
    test: function-relative-units.html
  - subtest: rem in a typed parameter
    test: function-relative-units.html
  - subtest: em within calc() in a typed parameter
    test: function-relative-units.html
  - subtest: em in a typed parameter, untyped return
    test: function-relative-units.html
  - subtest: em in a typed parameter default
    test: function-relative-units.html
  - subtest: em in a typed parameter of a nested function
    test: function-relative-units.html
  - subtest: em in a typed result
    test: function-relative-units.html
  - subtest: em within calc() in a typed result
    test: function-relative-units.html
  - subtest: em in an untyped local substituted into a typed result
    test: function-relative-units.html
  - subtest: em in an untyped parameter
    test: function-relative-units.html
  - subtest: em in an untyped result
    test: function-relative-units.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2068039
