links:
- product: firefox
  results:
  - subtest: Empty string results in a single empty token
    test: systemLanguage-parsing.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2033631
- product: firefox
  results:
  - subtest: 'BCP 47 prefix matching: user language prefix matches listed tag with
      extra subtag'
    test: systemLanguage-matching.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2051052
