links:
- product: firefox
  results:
  - test: text-spacing-trim-fallback-002.html?class=halt,htb
  - test: text-spacing-trim-fallback-002.html?class=halt,vrl
  - test: text-spacing-trim-fallback-002.html?class=chws,vrl
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2000582
- product: firefox
  results:
  - test: text-spacing-trim-001.html?class=chws,vrl
  - test: text-spacing-trim-001.html?class=halt,vrl
  - test: text-spacing-trim-dot-001.html?class=halt,vrl
  - test: text-spacing-trim-dot-001.html?class=chws,vrl
  - test: text-spacing-trim-narrow-001.html?class=halt,vrl
  - test: text-spacing-trim-span-001.html?class=space-first,halt,vrl
  - test: text-spacing-trim-span-001.html?class=chws,vrl
  - test: text-spacing-trim-span-001.html?class=trim-start,chws,vrl
  - test: text-spacing-trim-span-001.html?class=halt,vrl
  - test: text-spacing-trim-span-001.html?class=space-first,chws,vrl
  - test: text-spacing-trim-span-001.html?class=trim-start,halt,vrl
  - test: text-spacing-trim-start-oof-001.html?class=halt,vrl
  - test: text-spacing-trim-start-oof-001.html?class=chws,vrl
  - test: text-spacing-trim-subset-001.html?class=halt,vrl
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2042133
