links:
- product: firefox
  results:
  - test: column-subgrid-alignment-in-subgridded-axis-001.html
  - test: column-subgrid-stretch-001.html
  - test: row-subgrid-alignment-in-subgridded-axis-001.html
  - test: row-subgrid-stretch-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2051781
