links:
- product: firefox
  results:
  - test: url-image-referrer-policy-cross-origin.html
  - test: url-image-referrer-policy-same-origin.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2032486
