links:
- product: firefox
  results:
  - subtest: e.style['ruby-overhang'] = "auto" should set the property value
    test: ruby-overhang-valid.html
  - subtest: e.style['ruby-overhang'] = "none" should set the property value
    test: ruby-overhang-valid.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2031394
