links:
    - label: a11y
      results:
        - test: menu-content-model-violation.html
        - test: reparent-with-pending-violation-microtask.html
        - test: valid-submenu-invalid-root.html
    - label: accessibility
      results:
        - test: menu-content-model-violation.html
        - test: reparent-with-pending-violation-microtask.html
        - test: valid-submenu-invalid-root.html
