links:
    - product: chrome
      url: https://crbug.com/41482962
      results:
        - test: inheritance.html
        - test: link-parameters-computed.html
        - test: link-parameters-valid.html
