links:
    - product: safari
      url: https://bugs.webkit.org/show_bug.cgi?id=309041
      results:
        - test: focus-inside-hidden-svg-containers-03.html
        - test: focus-inside-hidden-svg-containers-01.html
