links:
    - label: a11y
      results:
        - test: ax-role-inference-children.html
        - test: ax-role-inference-item-elementinternals-nested.html
        - test: ax-role-inference-item-elementinternals-owner-implied.html
        - test: ax-role-inference-item-elementinternals.html
        - test: ax-role-inference-owner-elementinternals.html
        - test: ax-role-inference-owner.html
        - test: ax-role-inference-top-layer.html
        - test: feed-role-inference-item.html
        - test: feed-role-inference-owner.html
    - label: accessibility
      results:
        - test: ax-role-inference-children.html
        - test: ax-role-inference-item-elementinternals-nested.html
        - test: ax-role-inference-item-elementinternals-owner-implied.html
        - test: ax-role-inference-item-elementinternals.html
        - test: ax-role-inference-owner-elementinternals.html
        - test: ax-role-inference-owner.html
        - test: ax-role-inference-top-layer.html
        - test: feed-role-inference-item.html
        - test: feed-role-inference-owner.html
