links:
- product: chrome
  results:
  - test: clip-text-flex.html
  - test: clip-text-multi-line.html
  url: https://crbug.com/1275365
- product: firefox
  results:
  - test: clip-text-ellipsis.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1914493
- product: firefox
  results:
  - test: clip-text-text-emphasis.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1914494
- product: firefox
  results:
  - test: clip-border-area-border-shape.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2028091
- product: firefox
  results:
  - test: clip-text-descendants.html
  - test: clip-text-multiline-linebreak.html
  - test: clip-text-scaled.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2029359
- product: firefox
  results:
  - test: clip-border-shape-table-part-background.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2031610
- product: firefox
  results:
  - test: clip-border-area-border-shape-background-position.html
  - test: clip-border-area-border-shape-overflow.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2033754
