links:
- product: firefox
  results:
  - subtest: Measure target with value=content-height and wm=undefined
    test: responsive-iframe-value.tentative.html?value=content-height,300,200
  - subtest: Measure target with value=content-width and wm=undefined
    test: responsive-iframe-value.tentative.html?value=content-width,400,150
  - subtest: Measure target with value=content-inline-size and wm=vertical-rl
    test: responsive-iframe-value.tentative.html?value=content-inline-size,300,200,vertical-rl
  - subtest: Measure target with value=content-inline-size and wm=undefined
    test: responsive-iframe-value.tentative.html?value=content-inline-size,400,150
  - subtest: Measure target with value=content-block-size and wm=vertical-rl
    test: responsive-iframe-value.tentative.html?value=content-block-size,400,150,vertical-rl
  - subtest: Measure target with value=content-block-size and wm=undefined
    test: responsive-iframe-value.tentative.html?value=content-block-size,300,200
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2020881
- product: firefox
  results:
  - test: responsive-iframe-dynamic-remove.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2031952
- product: firefox
  results:
  - test: responsive-iframe-meta-after-head.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2031970
- product: firefox
  results:
  - test: responsive-iframe-dom-content-loaded.tentative.html
  - subtest: '`DOMContentLoaded` triggers resizing'
    test: responsive-iframe-dom-content-loaded.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2033704
- product: firefox
  results:
  - test: responsive-iframe-dom-content-loaded.html
  - subtest: '`DOMContentLoaded` triggers resizing'
    test: responsive-iframe-dom-content-loaded.html
  - subtest: Responsive iframe clears size during navigation to non-responsive page
    test: responsive-iframe-navigation-unsized.html?origin=same
  - subtest: Responsive iframe clears size during navigation to non-responsive page
    test: responsive-iframe-navigation-unsized.html?origin=cross
  - subtest: Responsive iframe preserves size during navigation
    test: responsive-iframe-navigation.html
  - subtest: '`window.requestResize()` from the parent frame throws DOM NotAllowedError'
    test: responsive-iframe-request-resize-error.html
  - subtest: '`window.requestResize()` from iframe without `responsive-embedded-sizing`
      meta tag throws DOM NotAllowedError'
    test: responsive-iframe-request-resize-error.html
  - subtest: Measure target with value=content-width and wm=undefined
    test: responsive-iframe-value.html?value=content-width,400,150
  - subtest: Measure target with value=content-inline-size and wm=undefined
    test: responsive-iframe-value.html?value=content-inline-size,400,150
  - subtest: Measure target with value=content-block-size and wm=vertical-rl
    test: responsive-iframe-value.html?value=content-block-size,400,150,vertical-rl
  - subtest: Measure target with value=content-height and wm=undefined
    test: responsive-iframe-value.html?value=content-height,300,200
  - subtest: Measure target with value=content-inline-size and wm=vertical-rl
    test: responsive-iframe-value.html?value=content-inline-size,300,200,vertical-rl
  - subtest: Measure target with value=content-block-size and wm=undefined
    test: responsive-iframe-value.html?value=content-block-size,300,200
  - test: responsive-iframe-cross-origin.sub.html
  - test: responsive-iframe-dynamic-remove.html
  - test: responsive-iframe-meta-after-head.html
  - test: responsive-iframe-request-resize.html
  - test: responsive-iframe.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040171
