links:
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2032062
  results:
  - test: column-subgrid-extra-margin-006.html
  - test: row-subgrid-extra-margin-001.html
  - test: row-subgrid-extra-margin-003.html
  - test: column-subgrid-extra-margin-003.html
  - test: column-subgrid-extra-margin-001.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2027012
  results:
  - test: grid-lanes-subgrid.html
