links:
- product: firefox
  results:
  - test: column-subgrid-extra-margin-006.html
  - test: row-subgrid-extra-margin-001.html
  - test: row-subgrid-extra-margin-003.html
  - test: column-subgrid-extra-margin-003.html
  - test: column-subgrid-extra-margin-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2032062
- product: firefox
  results:
  - test: grid-lanes-subgrid.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2027012
- product: firefox
  results:
  - test: grid-lanes-subgrid-intrinsic-sizing.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2032447
- product: firefox
  results:
  - test: column-subgrid-with-row-standalone-axis-size-002.html
  - test: column-subgrid-with-row-standalone-axis-size-003.html
  - test: column-subgrid-with-row-standalone-axis-size-004.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2039190
- product: firefox
  results:
  - test: grid-lanes-subgrid-flex.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040337
- product: firefox
  results:
  - test: column-subgrid-extra-margin-007.html
  - test: column-subgrid-extra-margin-009.html
  - test: row-subgrid-extra-margin-006.html
  - test: row-subgrid-extra-margin-007.html
  - test: row-subgrid-extra-margin-008.html
  - test: row-subgrid-extra-margin-009.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040527
- product: firefox
  results:
  - test: column-auto-track-sizing-002.html
  - test: row-auto-track-sizing-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040535
- product: firefox
  results:
  - test: row-auto-placed-subgrid-inherited-tracks-003.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2048167
- product: firefox
  results:
  - test: auto-track-sizing-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2050113
