links:
- product: firefox
  results:
  - test: column-subgrid-standalone-row-axis-size-001.html
  - test: row-subgrid-standalone-column-axis-size-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2036245
