links:
- product: firefox
  results:
  - test: column-multi-lane-fragmentation-001.html
  - test: column-multi-lane-fragmentation-002.html
  - test: column-multi-lane-fragmentation-004.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2059887
- product: firefox
  results:
  - test: row-multi-lane-fragmentation-001.html
  - test: row-multi-lane-fragmentation-003.html
  - test: row-multi-lane-fragmentation-004.html
  - test: row-multi-lane-fragmentation-005.html
  - test: row-multi-lane-fragmentation-006.html
  - test: row-single-lane-fragmentation-001.html
  - test: row-single-lane-fragmentation-003.html
  - test: row-single-lane-fragmentation-004.html
  - test: row-single-lane-fragmentation-005.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2068606
