links:
- product: firefox
  results:
  - subtest: Property grid-template-columns value 'subgrid'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid [a]'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid [a] [b]'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid [a] [] [b]'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid repeat(auto-fill, [a])'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid repeat(2, [a] [b])'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-columns value 'subgrid [a] repeat(auto-fill, [b])
      [c]'
    test: grid-lanes-column-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid [a]'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid [a] [b]'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid [a] [] [b]'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid repeat(auto-fill, [a])'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid repeat(2, [a] [b])'
    test: grid-lanes-row-subgrid-computed.html
  - subtest: Property grid-template-rows value 'subgrid [a] repeat(auto-fill, [b])
      [c]'
    test: grid-lanes-row-subgrid-computed.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040942
