links:
    - label: a11y
      results:
        - test: picture-aria-role-application-novalid.html
        - test: picture-aria-role-button-novalid.html
        - test: picture-aria-role-img-novalid.html
        - test: picture-aria-role-presentation-novalid.html
        - test: picture-aria-role-region-novalid.html
        - test: source-aria-role-img-novalid.html
        - test: source-aria-role-presentation-novalid.html
    - label: accessibility
      results:
        - test: picture-aria-role-application-novalid.html
        - test: picture-aria-role-button-novalid.html
        - test: picture-aria-role-img-novalid.html
        - test: picture-aria-role-presentation-novalid.html
        - test: picture-aria-role-region-novalid.html
        - test: source-aria-role-img-novalid.html
        - test: source-aria-role-presentation-novalid.html
