links:
- product: firefox
  results:
  - test: animation-trigger-addAnimation.tentative.html
  - test: animation-trigger-multiple-animations.tentative.html
  - test: animation-trigger-multiple-triggers.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1970415
- product: firefox
  results:
  - test: animation-trigger-disarmed-by-apis.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1974129
- product: firefox
  results:
  - subtest: contain calc(0% + 100px) matches contain 100px at offset before range
      under CSS zoom
    test: animation-trigger-calc-with-zoom.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2022820
- product: firefox
  results:
  - test: animation-trigger-fill-mode-both.tentative.html
  - test: animation-trigger-fill-mode-none.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2038300
- product: firefox
  results:
  - subtest: Added scope prevents subtree from searching for external trigger
    test: trigger-scope-add.tentative.html
  - subtest: Added scope prevents external references from finding trigger within
      scope.
    test: trigger-scope-add.tentative.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2042634
