links:
- product: firefox
  results:
  - test: column-fill-reverse-orthogonal-container-001.html
  - test: column-fill-reverse-out-of-flow-definite-size-001.html
  - test: row-fill-reverse-indefinite-size-001.html
  - test: row-fill-reverse-orthogonal-container-001.html
  - test: row-fill-reverse-orthogonal-container-002.html
  - test: row-fill-reverse-out-of-flow-definite-size-001.html
  - test: row-fill-reverse-out-of-flow-indefinite-size-001.html
  - test: row-fill-reverse-track-reverse-indefinite-size-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2036243
