links:
    - label: a11y
      results:
        - test: role-updates-after-move.html
    - label: accessibility
      results:
        - test: role-updates-after-move.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1894184
      results:
        - test: css-transition-cross-document.html
