links:
- product: chrome
  url: https://crbug.com/571722
  results:
  - test: setrequestheader-header-allowed.htm
    subtest: 'XMLHttpRequest: setRequestHeader() - headers that are allowed (User-Agent)'
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=209801
  results:
  - test: header-user-agent-sync.htm
    status: FAIL
- product: chrome
  url: https://crbug.com/651750
  results:
  - test: responseXML-unavailable-in-worker.html
    status: FAIL
  - test: send-content-type-charset.htm
    status: FAIL
  - test: responsetype.any.worker.html
    status: FAIL
  - test: send-authentication-cors-setrequestheader-no-cred.htm
    status: FAIL
  - test: event-readystatechange-loaded.any.html
    status: FAIL
  - test: open-during-abort-processing.htm
    status: FAIL
  - test: event-readystatechange-loaded.any.worker.html
    status: FAIL
  - test: abort-after-send.any.html
    status: FAIL
  - test: response-data-progress.htm
    status: FAIL
  - test: responseType-document-in-worker.html
    status: FAIL
  - test: setrequestheader-combining.window.html
    status: FAIL
  - test: idlharness.any.worker.html
    status: FAIL
  - test: responsexml-media-type.htm
    status: FAIL
- product: chrome
  url: https://crbug.com/787704
  results:
  - test: send-redirect-to-cors.htm
    status: FAIL
- product: chrome
  url: https://crbug.com/699085
  results:
  - test: overridemimetype-blob.html
    status: FAIL
- product: chrome
  url: https://crbug.com/588103
  results:
  - test: response-json.htm
    status: FAIL
- product: chrome
  url: https://crbug.com/881180
  results:
  - test: open-url-multi-window-4.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1842970
  results:
  - test: abort-after-receive.any.worker.html
  - test: abort-after-send.any.worker.html
  - test: abort-during-upload.any.worker.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1397646
  results:
  - test: status.h2.window.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=697151
  results:
  - test: send-sync-blocks-async.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1362343
  results:
  - test: open-url-multi-window-6.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1366966
  results:
  - test: send-sync-blocks-async.htm
  - test: open-url-multi-window-4.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=580353
  results:
  - test: access-control-preflight-credential-async.htm
  - test: access-control-preflight-credential-sync.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1453318
  results:
  - test: headers-normalize-response.htm
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1697421
  results:
  - test: getallresponseheaders.htm
  - test: getresponseheader.any.html
  - test: getresponseheader.any.worker.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1846092
  results:
  - test: xhr-timeout-longtask.any.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1854695
  results:
  - test: send-redirect.htm
    subtest: 'XMLHttpRequest: send() - Redirects (basics) (300 does not redirect)'
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=254864
  results:
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Int8Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Uint8Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Uint8ClampedArray backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Uint16Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Int16Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a BigInt64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Int32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Uint32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Float32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a BigUint64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a DataView backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.worker.html
    subtest: sending a Float64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Int8Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Uint8Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Uint8ClampedArray backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Int16Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Uint16Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Int32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Uint32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a BigUint64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a BigInt64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Float32Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a Float64Array backed by a SharedArrayBuffer
  - test: send-data-sharedarraybuffer.any.html
    subtest: sending a DataView backed by a SharedArrayBuffer
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1893900
  results:
  - test: overridemimetype-blob.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1833647
  results:
  - test: send-data-sharedarraybuffer.any.html
  - test: send-data-sharedarraybuffer.any.worker.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1833646
  results:
  - test: send-data-sharedarraybuffer.any.html
  - test: send-data-sharedarraybuffer.any.worker.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1915047
  results:
  - test: overridemimetype-blob.html
    subtest: '2) MIME types need to be parsed and serialized: TEXT/HTML;CHARSET=GBK'
  - test: overridemimetype-blob.html
    subtest: "26) MIME types need to be parsed and serialized: text/html;charset=
      \"\x7F;charset=GBK"
  - test: overridemimetype-blob.html
    subtest: "27) MIME types need to be parsed and serialized: text/html;charset=\"\x7F;charset=foo\";charset=GBK"
  - test: overridemimetype-blob.html
    subtest: '37) MIME types need to be parsed and serialized: text/html;charset=";charset=GBK'
  - test: overridemimetype-blob.html
    subtest: '44) MIME types need to be parsed and serialized: !#$%&''*+-.^_`|~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz/!#$%&''*+-.^_`|~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz;!#$%&''*+-.^_`|~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz=!#$%&''*+-.^_`|~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
  - test: overridemimetype-blob.html
    subtest: "45) MIME types need to be parsed and serialized: x/x;x=\"\t !\\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x80\x81\x82\x83\x84\N\x86\x87\x88\x89\x8A\x8B\x8C\x8D\x8E\x8F\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9A\x9B\x9C\x9D\x9E\x9F ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ\""
  - test: overridemimetype-blob.html
    subtest: '53) MIME types need to be parsed and serialized: text/html;test=ÿ;charset=gbk'
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2023146
  results:
  - test: xmlhttprequest-sync-default-permissions-policy.tentative.sub.html
    subtest: permissions policy "sync-xhr" can be disabled in cross-origin iframes
      using "allow" attribute.
  - test: xmlhttprequest-sync-default-permissions-policy.tentative.sub.html
    subtest: permissions policy "sync-xhr" can be disabled in same-origin iframes
      using "allow" attribute.
