links:
- product: firefox
  results:
  - test: grid-lanes-subgrid-001a.html
  - test: grid-lanes-subgrid-001b.html
  - test: grid-lanes-subgrid-001c.html
  - test: grid-lanes-subgrid-001d.html
  - test: grid-lanes-subgrid-002a.html
  - test: grid-lanes-subgrid-002b.html
  - test: grid-lanes-subgrid-002c.html
  - test: grid-lanes-subgrid-002d.html
  - test: grid-lanes-subgrid-002e.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2032447
