links:
- product: firefox
  results:
  - test: column-line-names-005.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2050726
- product: firefox
  results:
  - test: column-line-names-001.html
  - test: column-line-names-002.html
  - test: column-line-names-003.html
  - test: column-line-names-004.html
  - test: column-line-names-006.html
  - test: column-line-names-007.html
  - test: column-line-names-008.html
  - test: column-line-names-010.html
  - test: column-line-names-012.html
  - test: row-line-names-001.html
  - test: row-line-names-002.html
  - test: row-line-names-004.html
  - test: row-line-names-013.html
  - test: row-line-names-014.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2050332
