links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1463844
      results:
        - test: audio_has_no_subtitles.html
    - product: chrome
      url: https://crbug.com/1012242
      results:
        - test: basic.html
    - url: https://bugzilla.mozilla.org/show_bug.cgi?id=2060737
      label: 'Firefox: extra space between cues; probably a float/int bug'
      results:
        - test: 2_cues_overlapping_completely_move_up.html
        - test: 2_cues_overlapping_partially_move_down.html
        - test: 2_cues_overlapping_partially_move_up.html
    - url: https://github.com/web-platform-tests/wpt/pull/61482
      label: 'Once PR merges, these tests will be considered "verified" '
      results:
        - test: 2_cues_overlapping_completely_move_up.html
        - test: 2_cues_overlapping_partially_move_down.html
        - test: 2_cues_overlapping_partially_move_up.html
        - test: 2_tracks.html
        - test: 3_tracks.html
        - test: align_center_position_50.html
        - test: align_center.html
