links:
- product: firefox
  results:
  - subtest: Property path-length value 'none'
    test: path-length-computed.tentative.svg
  - subtest: e.style['path-length'] = "none" should set the property value
    test: path-length-valid.tentative.svg
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2052087
