links:
- product: firefox
  results:
  - test: column-grid-lanes-alignment-positioned-items-004.html
  - test: column-grid-lanes-justify-self-003.html
  - test: column-grid-lanes-alignment-positioned-items-001.html
  - test: row-grid-lanes-align-self-003.html
  - test: row-grid-lanes-alignment-positioned-items-004.html
  - test: row-grid-lanes-align-self-001.html
  - test: column-grid-lanes-alignment-positioned-items-002.html
  - test: column-grid-lanes-alignment-positioned-items-003.html
  - test: row-grid-lanes-alignment-positioned-items-003.html
  - test: row-grid-lanes-align-self-002.html
  - test: row-grid-lanes-alignment-positioned-items-001.html
  - test: row-grid-lanes-alignment-positioned-items-002.html
  - test: column-grid-lanes-justify-self-002.html
  - test: column-grid-lanes-justify-self-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1993591
- product: firefox
  results:
  - test: grid-lanes-justify-content-003.html
  - test: grid-lanes-justify-content-004.html
  - test: grid-lanes-align-content-001.html
  - test: grid-lanes-align-content-004.html
  - test: grid-lanes-align-content-002.html
  - test: grid-lanes-justify-content-002.html
  - test: grid-lanes-justify-content-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1991204
- product: firefox
  results:
  - test: grid-lanes-align-content-003.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1972618
- product: firefox
  results:
  - test: column-overflow-alignment-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2000655
- product: firefox
  results:
  - test: column-overflow-alignment-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2001786
- product: firefox
  results:
  - test: column-fill-reverse-justify-content-001.html
  - test: column-fill-reverse-justify-content-002.html
  - test: column-fill-reverse-justify-items-001.html
  - test: column-fill-reverse-justify-items-002.html
  - test: column-fill-reverse-justify-items-003.html
  - test: column-fill-reverse-justify-self-001.html
  - test: row-fill-reverse-align-content-001.html
  - test: row-fill-reverse-align-content-002.html
  - test: row-fill-reverse-align-items-001.html
  - test: row-fill-reverse-align-items-002.html
  - test: row-fill-reverse-align-items-003.html
  - test: row-fill-reverse-align-self-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2026970
- product: firefox
  results:
  - test: grid-lanes-align-content-refinalize-row-geometry-001.html
  - test: grid-lanes-align-content-refinalize-row-geometry-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2031923
- product: firefox
  results:
  - test: row-fill-reverse-align-content-indefinite-size-001.html
  - test: row-fill-reverse-align-items-indefinite-size-001.html
  - test: row-fill-reverse-align-items-indefinite-size-002.html
  - test: row-fill-reverse-align-self-indefinite-size-001.html
  - test: row-fill-reverse-justify-content-indefinite-size-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2036243
