links:
- product: firefox
  results:
  - test: preview-navigation-query.tentative.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2028792
- product: firefox
  results:
  - test: preview-finished-before-swap.tentative.https.html
  - test: swap-continues-when-skipping-preview.tentative.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2036830
