links:
- product: firefox
  results:
  - test: instant-transition-finish-before-swap.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1990355
- label: interop-2026-view-transitions
  results:
  - test: instant-transition-finish-before-swap.https.html
- product: firefox
  results:
  - test: preview-navigation-query.tentative.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2028792
