links:
- product: firefox
  results:
  - subtest: '#gridLanes 1'
    test: grid-lanes-add-child-dynamic-change.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-add-child-dynamic-change.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-change-intrinsic-size-with-auto-repeat-tracks-001.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-change-intrinsic-size-with-auto-repeat-tracks-001.html
  - subtest: '#gridLanes 3'
    test: grid-lanes-change-intrinsic-size-with-auto-repeat-tracks-001.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-column-tracks-recompute-child-positions-001.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-column-tracks-recompute-child-positions-001.html
  - subtest: '#gridLanes 3'
    test: grid-lanes-column-tracks-recompute-child-positions-001.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-direction-dynamic-change-002.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-direction-dynamic-change-002.html
  - subtest: '#gridLanes 3'
    test: grid-lanes-direction-dynamic-change-002.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-direction-dynamic-change-003.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-direction-dynamic-change-003.html
  - subtest: '#gridLanes 3'
    test: grid-lanes-direction-dynamic-change-003.html
  - subtest: '#gridLanes1 1'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes1 2'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes1 3'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes1 4'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes1 5'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes2 6'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes2 7'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes2 8'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanesSized 10'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanesSized 11'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanesSized 12'
    test: grid-lanes-grid-template-columns-changes-001.html
  - subtest: '#gridLanes1 1'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes1 2'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes1 3'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes1 4'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes1 5'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes2 6'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes2 7'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes2 8'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanesSized 10'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanesSized 11'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanesSized 12'
    test: grid-lanes-grid-template-rows-changes-001.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-remove-child-dynamic-change.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-remove-child-dynamic-change.html
  - subtest: '#gridLanes 1'
    test: grid-lanes-row-tracks-recompute-child-positions-001.html
  - subtest: '#gridLanes 2'
    test: grid-lanes-row-tracks-recompute-child-positions-001.html
  - subtest: '#gridLanes 3'
    test: grid-lanes-row-tracks-recompute-child-positions-001.html
  - test: grid-lanes-direction-dynamic-change-001.html
  - test: grid-lanes-pack-dynamic-change.html
  - test: grid-lanes-reorder-child-dynamic-change.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2041293
