links:
- product: firefox
  results:
  - subtest: H.264 and VP8 should be negotiated after handshake
    test: video-codecs.https.html
  - subtest: All H.264 codecs MUST include profile-level-id
    test: video-codecs.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1534687
- product: firefox
  results:
  - subtest: H.264 and VP8 should be supported in initial offer
    test: video-codecs.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1534688
- product: firefox
  results:
  - subtest: Adding only caller -> callee candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Adding only callee -> caller candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Explicit offer/answer exchange gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Adding callee -> caller candidates from end-of-candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: tlsVersion is acceptable on data-only
    test: crypto-suite.https.html
  - subtest: tlsVersion is acceptable on video-only
    test: crypto-suite.https.html
  - subtest: dtlsCipher is acceptable on data-only
    test: crypto-suite.https.html
  - subtest: dtlsCipher is acceptable on video-only
    test: crypto-suite.https.html
  - subtest: srtpCipher is acceptable on data-only
    test: crypto-suite.https.html
  - subtest: srtpCipher is acceptable on video-only
    test: crypto-suite.https.html
  - subtest: tlsGroup is acceptable on data-only
    test: crypto-suite.https.html
  - subtest: tlsGroup is acceptable on video-only
    test: crypto-suite.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1278299
- product: firefox
  results:
  - subtest: PC should enter disconnected state when a failing candidate is sent
    test: ice-state.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1557053
- product: firefox
  results:
  - subtest: createOffer() with multiple send encodings should create simulcast offer
    test: simulcast-answer.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1547036
- product: firefox
  results:
  - subtest: not negotiating BUNDLE creates two separate ice and dtls transports
    test: bundle.https.html?rest
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1307996
- product: firefox
  results:
  - subtest: PC with setup=actpass should have a dtlsRole of client
    test: dtls-setup.https.html
  - subtest: PC with setup=active should have a dtlsRole of server
    test: dtls-setup.https.html
  - subtest: PC with setup=passive should have a dtlsRole of client
    test: dtls-setup.https.html
  - subtest: dtlsRole is `unknown` before negotiation of the DTLS handshake
    test: dtls-setup.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1225723
- product: firefox
  results:
  - test: handover.html
  - subtest: Handover with datachannel reinitiated from new callee completes
    test: handover-datachannel.html
  url: https://github.com/web-platform-tests/wpt/issues/37561
- product: firefox
  results:
  - subtest: SetStreams with a stream produces MSID with a stream ID
    test: msid-generate.html
  - subtest: SetStreams with two streams produces two MSID lines
    test: msid-generate.html
  - subtest: SetStreams with the stream twice produces single MSID with a stream ID
    test: msid-generate.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1510802
- product: firefox
  results:
  - subtest: Can demux two video tracks with different payload types on a bundled
      connection
    test: rtp-demuxing.html
  - subtest: Level 1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 3 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 4 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 5 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 6 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 1.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 1.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 1.3 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 2.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 2.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 3.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 3.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 4.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 4.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 5.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 5.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?interop-2026
  - subtest: Level 6.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 6.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1531460
- product: firefox
  results:
  - subtest: Connect audio and video to two independent PeerConnections
    test: split.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1643050
- product: firefox
  results:
  - subtest: RTP header extension urn:3gpp:video-orientation is present in offer
    test: rtp-extension-support.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1340372
- product: firefox
  results:
  - subtest: setRemoteDescription parses max-fr and max-fs fmtp parameters
    test: vp8-fmtp.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1531464
- product: firefox
  results:
  - subtest: bundles on the first transport and closes the second
    test: bundle.https.html?interop-2026
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1805480
- product: firefox
  results:
  - subtest: max-bundle with an offer without bundle only negotiates the first m-line
    test: bundle.https.html?rest
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1805484
- product: firefox
  results:
  - subtest: AddTrack with the stream twice produces single MSID with a stream ID
    test: msid-generate.html
  - subtest: AddTransceiver with the stream twice produces single MSID with a stream
      ID
    test: msid-generate.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1808989
- product: firefox
  results:
  - subtest: setRemoteDescription with a ice-ufrag containing a non-ice-char fails
    test: ice-ufragpwd.html
  - subtest: setRemoteDescription with a ice-pwd containing a non-ice-char fails
    test: ice-ufragpwd.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1617686
- product: firefox
  results:
  - subtest: Connection fails if one side provides a wrong DTLS fingerprint
    test: dtls-fingerprint-validation.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1635922
- product: firefox
  results:
  - subtest: setRemoteDescription with a codec in the range 64-95 throws an InvalidAccessError
    test: rtp-payloadtypes.html?rest
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1806181
- product: firefox
  results:
  - subtest: Unknown media types are rejected with the port set to 0
    test: unknown-mediatypes.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1806185
- product: chrome
  results:
  - subtest: Using the ~rid SDP syntax in a remote offer does not control the local
      encodings active flag
    test: simulcast-answer.html
  url: https://issues.chromium.org/343086063
- product: chrome
  results:
  - subtest: Level 2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 3 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 2.1 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  - subtest: Level 2.2 H264 video is appropriately constrained
    test: h264-profile-levels.https.html?rest
  url: https://issues.webrtc.org/issues/42224482
- product: firefox
  results:
  - subtest: Adding only caller -> callee candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Adding only callee -> caller candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Adding callee -> caller candidates from end-of-candidates gives a connection
    test: candidate-exchange.https.html?interop-2026
  - subtest: Explicit offer/answer exchange gives a connection
    test: candidate-exchange.https.html?interop-2026
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1307994
- label: interop-2026-webrtc
  results:
  - test: handover.html
  - test: rtp-payloadtypes.html?interop-2026
  - test: bundle.https.html?interop-2026
  - test: rtp-demuxing.html
  - test: video-codecs.https.html
  - test: codecs-subsequent-offer.https.html
  - test: handover-datachannel.html
  - test: rtp-headerextensions.html
  - test: candidate-exchange.https.html?interop-2026
  - test: crypto-suite.https.html
  - test: dtls-setup.https.html
  - test: rtp-extension-support.html
  - test: unknown-mediatypes.html
  - test: additional-codecs.html
- product: firefox
  results:
  - status: CRASH
    test: h264-profile-levels.https.html?rest
  - status: CRASH
    test: h264-profile-levels.https.html?interop-2026
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2063626
