links:
    - product: chrome
      url: https://crbug.com/847357
      results:
        - test: cache-keys-attributes-for-service-worker.https.html
    - product: chrome
      url: https://issues.chromium.org/issues/41340002
      results:
        - test: cache-add.https.any.sharedworker.html
