links:
- product: firefox
  results:
  - subtest: Text selection by a pointer device should work correctly
    test: hittest.html
  - subtest: '"text-autospace" and "consistent" work fine'
    test: text-autospace.html
  - subtest: '"text-autospace" and "per-line-all" work fine'
    test: text-autospace.html
  - subtest: '[consistent] Check that text-spacing-trim: trim-start scales larger
      than none because of trimmed start margin'
    test: text-spacing-trim-fit-width.html
  - subtest: '[per-line-all] Check that text-spacing-trim: trim-start scales larger
      than none because of trimmed start margin'
    test: text-spacing-trim-fit-width.html
  - test: grow-consistent.html
  - test: grow-per-line-all-line-height.html
  - test: grow-per-line-all.html
  - test: grow-per-line.html
  - test: selection-highlight-painting.html
  - test: shrink-consistent.html
  - test: shrink-per-line-all.html
  - test: spacing.html
  - test: text-align.html
  - test: text-box.html
  - test: writing-mode.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2036796
- product: firefox
  results:
  - test: text-decoration-thickness.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040172
- product: firefox
  results:
  - test: background-image.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040157
- product: firefox
  results:
  - subtest: line-height:normal should be scaled
    test: line-height.html
  - subtest: line-height:<number> should be scaled
    test: line-height.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2040113