links:
- product: firefox
  results:
  - test: url-image-cross-origin-anonymous.sub.html
  - test: url-image-cross-origin-use-credentials.sub.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2033809
