links:
- product: chrome
  results:
  - test: text-complex-001.svg
  - test: text-complex-002.svg
  - test: text-shape-inside-001.svg
  - test: text-shape-inside-002.svg
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=875411
- product: chrome
  results:
  - test: text-multiline-001.svg
  - test: text-multiline-002.svg
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=366558
- product: chrome
  results:
  - test: text-inline-size-002.svg
  - test: text-inline-size-005.svg
  - test: text-inline-size-006.svg
  - test: text-inline-size-007.svg
  - test: text-inline-size-101.svg
  - test: text-inline-size-201.svg
  - test: text-inline-size-001.svg
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=366553
- product: chrome
  results:
  - test: text-xml-space-001.svg
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=699040
- product: chrome
  results:
  - test: textpath-shape-001.svg
  - test: textpath-side-001.svg
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=366559
- product: safari
  results:
  - test: text-xml-space-001.svg
  url: https://bugs.webkit.org/show_bug.cgi?id=264071
- product: firefox
  results:
  - test: textLength-list-x-spacingAndGlyphs.svg
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2047340
