links:
- product: firefox
  results:
  - test: column-gap-decorations-041.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2066258
- product: firefox
  results:
  - test: column-gap-decorations-list-grid-axis.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2066260
- product: firefox
  results:
  - test: column-gap-decorations-break-normal.html
  - test: column-gap-decorations-overlap-column-over-row.html
  - test: row-gap-decorations-break-normal.html
  - test: row-gap-decorations-overlap-column-over-row.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2067826
