links:
- product: firefox
  results:
  - test: column-gap-decorations-041.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2066258
- product: firefox
  results:
  - test: column-gap-decorations-list-grid-axis.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2066260
- product: firefox
  results:
  - test: column-gap-decorations-break-normal.html
  - test: column-gap-decorations-overlap-column-over-row.html
  - test: row-gap-decorations-break-normal.html
  - test: row-gap-decorations-overlap-column-over-row.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2067826
- product: firefox
  results:
  - test: column-gap-decorations-inset-non-overlapping-gutter-percentage.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2068918
- product: firefox
  results:
  - test: column-gap-decorations-rule-visibility-items-all-001.html
  - test: column-gap-decorations-rule-visibility-items-all-002.html
  - test: column-gap-decorations-rule-visibility-items-around-001.html
  - test: column-gap-decorations-rule-visibility-items-between-003.html
  - test: gap-decorations-rule-visibility-items-normal-001.html
  - test: row-gap-decorations-rule-visibility-items-all-001.html
  - test: row-gap-decorations-rule-visibility-items-between-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2073420
- product: firefox
  results:
  - test: column-gap-decorations-rule-visibility-items-empty-all.html
  - test: row-gap-decorations-rule-visibility-items-all-002.html
  - test: row-gap-decorations-rule-visibility-items-around-003.html
  - test: row-gap-decorations-rule-visibility-items-between-003.html
  - test: row-gap-decorations-rule-visibility-items-empty-all.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2074811
- product: firefox
  results:
  - test: column-gap-decorations-auto-fit-collapsed-leading.html
  - test: column-gap-decorations-auto-fit-collapsed-list.html
  - test: column-gap-decorations-auto-fit-dynamic-add.html
  - test: row-gap-decorations-auto-fit-collapsed-leading.html
  - test: row-gap-decorations-auto-fit-collapsed-list.html
  - test: row-gap-decorations-auto-fit-collapsed-middle.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=2074815
